Fix compilation error "qobject.h:300:9: error: static assertion failed: Signal and slot arguments are not compatible."
(cherry picked from commit 841b6f6e19d829d6ab9ee13a5d4b0bcc9f1ee2df)