Put the operator== for DefaultVariableModel::Variable to the namespace
clang is stricter when compiling, and fails due to Argument-Dependent
Lookup issues.

/usr/include/QtCore/qlist.h:885:20: error: call to function 'operator=='
that is neither visible in the template definition nor found
      by argument-dependent lookup
        if (i->t() == t)
                   ^
/tmp/clang-tests/cantor/src/lib/defaultvariablemodel.cpp:153:23: note:
in instantiation of member function
      'QList<Cantor::DefaultVariableModel::Variable>::contains'
requested here
    if ( d->variables.contains(variable) )
                      ^
/tmp/clang-tests/cantor/src/lib/defaultvariablemodel.cpp:194:6: note:
'operator==' should be declared prior to the call site or in
      namespace 'Cantor'
bool operator==(const Cantor::DefaultVariableModel::Variable& one, const
Cantor::DefaultVariableModel::Variable& other)
     ^

This is the same problem fixed by commit c3e23ca to kde-baseapps. More
information can be found in http://www.gotw.ca/publications/mill08.htm.

(cherry picked from commit e8bb00ba5960a4f0811dfd401677d5d3bda2eb6a)